# frontend/Dockerfile
FROM node:18 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build --prod

# Stage 2 - serve with Nginx
FROM nginx:alpine
COPY --from=build /app/dist/hrms /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
